# Generated by Django 4.0.6 on 2022-07-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_member_posts_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AlterField(
            model_name='profile',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.authors'),
        ),
    ]
